from itertools import chain
def make_iterables_to_chain():
    odd_numbers = []
    even_numbers = []
    
    for i in range(100):
        if i % 2 == 0:
            even_numbers.append(i)
        else:
            odd_numbers.append(i)
            
    yield even_numbers
    yield odd_numbers
    
chained_iterables = chain.from_iterable(make_iterables_to_chain())
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")
print(f"calling next fromt the generators:- {next(chained_iterables)}")


